# Mod
mod_id = clienttweaks
mod_name = Client Tweaks
mod_author = BlayTheNinth
credits = BlayTheNinth
description=There, I fixed Minecraft for you. Various optional tweaks to improve Minecraft Quality of Life.
version = 26.2.0.2
group = net.blay09.mods
homepage=https://mods.twelveiterations.com/minecraft/client-tweaks
sources=https://github.com/TwelveIterations/ClientTweaks
issues=https://github.com/TwelveIterations/ClientTweaks/issues
discord = https://discord.gg/VAfZ2Nau6j
license=All Rights Reserved

# Publishing
curseforge_project_id = 251407
curseforge_environments = Client
modrinth_project_id = vPNqo58Q
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Build
java_version = 25
neoforge_snapshot_url =
include_fabric=true
include_neoforge=true
include_forge=false

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
