# Mod
mod_id = clienttweaks
mod_name = Client Tweaks
mod_main=ClientTweaks
description=There, I fixed Minecraft for you. Various optional tweaks to improve Minecraft Quality of Life.
version = 21.4.7
group = net.blay09.mods
homepage=https://mods.twelveiterations.com/mc/client-tweaks
sources=https://github.com/TwelveIterationMods/ClientTweaks
issues=https://github.com/TwelveIterationMods/ClientTweaks/issues
license=All Rights Reserved

# Publishing
curseforge_release_type = release
curseforge_project_id = 251407
modrinth_release_type = release
modrinth_project_id = vPNqo58Q

# Minecraft
minecraft_version = 1.21.4
minimum_minecraft_version = 1.21.4
minecraft_versions = 1.21.4
minecraft_version_range = [1.21.4,)
pack_format_number = 18
java_version = 21

# Balm
balm_version = 21.4.31-SNAPSHOT
balm_version_range = [21.4.0,)

# Forge
forge_version = 54.0.16
forge_version_range = [54,)
forge_loader_version_range = [52,)

# NeoForge
neoforge_version = 21.4.54-beta
neoforge_version_range = [21,)
neoforge_loader_version_range = [1,)

# Fabric
fabric_version = 0.114.2+1.21.4
fabric_loader_version = 0.16.10

# Dependencies
mixin_version=0.8.5
modmenu_version=9.0.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
mod_author = BlayTheNinth
credits = BlayTheNinth
kuma_version = [21.4,21.5)
neo_form_version = 1.21.4-20241203.161809
parchment_minecraft = 1.21.4
parchment_version = 2025.01.05